import React from 'react'
import "./endText.scss"

export default function EndText() {
  return (
    <div className="end">
    <p>
      · WEB DEVELOPER · FRONTEND DEVELOPER · BACK-END DEVELOPER ·FULL
      STACK DEVELOPER · WEB DEVELOPER · FRONTEND DEVELOPER · BACK-END
      DEVELOPER ·FULL STACK DEVELOPER · WEB DEVELOPER · FRONTEND DEVELOPER
      · BACK-END DEVELOPER ·FULL STACK DEVELOPER · WEB DEVELOPER ·
      FRONTEND DEVELOPER · BACK-END DEVELOPER ·FULL STACK DEVELOPER ·
    </p>
  </div>
  )
}
